### ISSUE TITLE
Cesium can not be displayed

### ISSUE THREAD

**Issue by 912807862** [KhronosGroup/glTF-Tutorials#18] opened 2018-08-28 03:01 UTC
Cesium can not be displayed，Can be displayed in threejs

**Comment by 912807862** [comment] 2018-08-28 03:02
{
  "scenes" : [
    {
      "nodes" : [ 0 ]
    }
  ],
  
  "nodes" : [
    {
      "mesh" : 0
    }
  ],
  
  "meshes" : [
    {
      "primitives" : [ {
        "attributes" : {
          "POSITION" : 1
        },
        "indices" : 0
      } ]
    }
  ],

  "buffers" : [
    {
      "uri" : "data:application/octet-stream;base64,AAABAAIAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAACAPwAAAAA=",
      "byteLength" : 44
    }
  ],
  "bufferViews" : [
    {
      "buffer" : 0,
      "byteOffset" : 0,
      "byteLength" : 6,
      "target" : 34963
    },
    {
      "buffer" : 0,
      "byteOffset" : 8,
      "byteLength" : 36,
      "target" : 34962
    }
  ],
  "accessors" : [
    {
      "bufferView" : 0,
      "byteOffset" : 0,
      "componentType" : 5123,
      "count" : 3,
      "type" : "SCALAR",
      "max" : [ 2 ],
      "min" : [ 0 ]
    },
    {
      "bufferView" : 1,
      "byteOffset" : 0,
      "componentType" : 5126,
      "count" : 3,
      "type" : "VEC3",
      "max" : [ 1.0, 1.0, 0.0 ],
      "min" : [ 0.0, 0.0, 0.0 ]
    }
  ],
  
  "asset" : {
    "version" : "2.0"
  }
}

**Comment by pjcozzi** [comment] 2018-08-28 11:10
Hi, could you please submit an issue in the Cesium repo? https://github.com/AnalyticalGraphicsInc/cesium

**Comment by emackey** [comment] 2018-08-28 13:45
Actually this is a duplicate of https://github.com/AnalyticalGraphicsInc/cesium/issues/6891, where the glTF default material was broken in Cesium.  It is already fixed in master and will be released on September 4th.

**Closed by emackey** 2018-08-28 13:45 UTC

**Comment by 912807862** [comment] 2018-09-03 11:17
@emackey ok  thanks
